#### Dataframe and series

#### from dictionary to df using pandas

In [7]:
pop_dict = {
    "Country": ["Sub-Saharan Africa", "Finland", "Gabon", "Burkina Faso", "Pakistan"],
    "1960": [227948869.0, 4429634.0, 513340.0, 4783259.0, 45954226.0],
    "1970": [293900563.0, 4606307.0, 597192.0, 5611666.0, 59290872.0],
    "1980": [388793467.0, 4779535.0, 749078.0, 6932967.0, 80624057.0],
    "1990": [516629688.0, 4986431.0, 983028.0, 9131361.0, 115414069.0],
    "2000": [671212486.0, 5176209.0, 1272935.0, 11882888.0, 154369924.0],
    "2010": [879797419.0, 5363352.0, 1711105.0, 16116845.0, 194454498.0],
    "2020": [1151302081.0, 5529543.0, 2292573.0, 21522626.0, 227196741.0]
}

In [8]:
import pandas as pd
import numpy as np

In [9]:
df = pd.DataFrame(pop_dict) #since dictionaries have the key with col name

df.head()

,Country,1960,1970,1980,1990,2000,2010,2020
0,Sub-Saharan Africa,227948869.0,293900563.0,388793467.0,516629688.0,671212486.0,879797419.0,1.151302e+09
1,Finland,4429634.0,4606307.0,4779535.0,4986431.0,5176209.0,5363352.0,5.529543e+06
2,Gabon,513340.0,597192.0,749078.0,983028.0,1272935.0,1711105.0,2.292573e+06
3,Burkina Faso,4783259.0,5611666.0,6932967.0,9131361.0,11882888.0,16116845.0,2.152263e+07
4,Pakistan,45954226.0,59290872.0,80624057.0,115414069.0,154369924.0,194454498.0,2.271967e+08

In [10]:
#using the name of the col to get the series
df['Country']

0    Sub-Saharan Africa
1               Finland
2                 Gabon
3          Burkina Faso
4              Pakistan
Name: Country, dtype: object

In [11]:
#we can also get by "." dot notation for non-numeric named columns
df.Country

0    Sub-Saharan Africa
1               Finland
2                 Gabon
3          Burkina Faso
4              Pakistan
Name: Country, dtype: object

In [28]:
# you will get error if you numeric column name
df.1960

SyntaxError: invalid syntax (1527332682.py, line 2)

In [13]:
#getting list of indices and columns

print(df.index) # this gives the range of the index like start, stop and step

print(df.columns) # list of columns

RangeIndex(start=0, stop=5, step=1)
Index(['Country', '1960', '1970', '1980', '1990', '2000', '2010', '2020'], dtype='object')

In [14]:
# Series also have indices
print(df["Country"].index) #gives rangeindex

RangeIndex(start=0, stop=5, step=1)

In [15]:
# return as list
df.columns.to_list()

['Country', '1960', '1970', '1980', '1990', '2000', '2010', '2020']

In [16]:
#return numpy array
df["1960"].to_numpy()

array([2.27948869e+08, 4.42963400e+06, 5.13340000e+05, 4.78325900e+06,
       4.59542260e+07])

In [17]:
# we can set the new indices using pandas
df.set_index(pd.Index(["a","b","c","d","e"]))

,Country,1960,1970,1980,1990,2000,2010,2020
a,Sub-Saharan Africa,227948869.0,293900563.0,388793467.0,516629688.0,671212486.0,879797419.0,1.151302e+09
b,Finland,4429634.0,4606307.0,4779535.0,4986431.0,5176209.0,5363352.0,5.529543e+06
c,Gabon,513340.0,597192.0,749078.0,983028.0,1272935.0,1711105.0,2.292573e+06
d,Burkina Faso,4783259.0,5611666.0,6932967.0,9131361.0,11882888.0,16116845.0,2.152263e+07
e,Pakistan,45954226.0,59290872.0,80624057.0,115414069.0,154369924.0,194454498.0,2.271967e+08

In [18]:
#but the original df is not changed since we didnt assign the last change to the df
df.head()

,Country,1960,1970,1980,1990,2000,2010,2020
0,Sub-Saharan Africa,227948869.0,293900563.0,388793467.0,516629688.0,671212486.0,879797419.0,1.151302e+09
1,Finland,4429634.0,4606307.0,4779535.0,4986431.0,5176209.0,5363352.0,5.529543e+06
2,Gabon,513340.0,597192.0,749078.0,983028.0,1272935.0,1711105.0,2.292573e+06
3,Burkina Faso,4783259.0,5611666.0,6932967.0,9131361.0,11882888.0,16116845.0,2.152263e+07
4,Pakistan,45954226.0,59290872.0,80624057.0,115414069.0,154369924.0,194454498.0,2.271967e+08

In [19]:
#changing the country as indices
df = df.set_index("Country")
df.head()

,1960,1970,1980,1990,2000,2010,2020
Country,,,,,,,
Sub-Saharan Africa,227948869.0,293900563.0,388793467.0,516629688.0,671212486.0,879797419.0,1.151302e+09
Finland,4429634.0,4606307.0,4779535.0,4986431.0,5176209.0,5363352.0,5.529543e+06
Gabon,513340.0,597192.0,749078.0,983028.0,1272935.0,1711105.0,2.292573e+06
Burkina Faso,4783259.0,5611666.0,6932967.0,9131361.0,11882888.0,16116845.0,2.152263e+07
Pakistan,45954226.0,59290872.0,80624057.0,115414069.0,154369924.0,194454498.0,2.271967e+08

In [20]:
#resting the indices

df = df.reset_index()
df.head()

,Country,1960,1970,1980,1990,2000,2010,2020
0,Sub-Saharan Africa,227948869.0,293900563.0,388793467.0,516629688.0,671212486.0,879797419.0,1.151302e+09
1,Finland,4429634.0,4606307.0,4779535.0,4986431.0,5176209.0,5363352.0,5.529543e+06
2,Gabon,513340.0,597192.0,749078.0,983028.0,1272935.0,1711105.0,2.292573e+06
3,Burkina Faso,4783259.0,5611666.0,6932967.0,9131361.0,11882888.0,16116845.0,2.152263e+07
4,Pakistan,45954226.0,59290872.0,80624057.0,115414069.0,154369924.0,194454498.0,2.271967e+08

#### other ways to create a dataframe

In [21]:
pop_lists = [
    ["Sub-Saharan Africa", 227948869.0, 293900563.0, 388793467.0, 516629688.0, 671212486.0, 879797419.0, 1151302081.0],
    ["Finland", 4429634.0, 4606307.0, 4779535.0, 4986431.0, 5176209.0, 5363352.0, 5529543.0],
    ["Gabon", 513340.0, 597192.0, 749078.0, 983028.0, 1272935.0, 1711105.0, 2292573.0],
    ["Burkina Faso", 4783259.0, 5611666.0, 6932967.0, 9131361.0, 11882888.0, 16116845.0, 21522626.0],
    ["Pakistan", 45954226.0, 59290872.0, 80624057.0, 115414069.0, 154369924.0, 194454498.0, 227196741.0]
]

In [22]:
df1 = pd.DataFrame(pop_lists,columns= ['Country', '1960', '1970', '1980', '1990', '2000', '2010', '2020'])
df1.head()

,Country,1960,1970,1980,1990,2000,2010,2020
0,Sub-Saharan Africa,227948869.0,293900563.0,388793467.0,516629688.0,671212486.0,879797419.0,1.151302e+09
1,Finland,4429634.0,4606307.0,4779535.0,4986431.0,5176209.0,5363352.0,5.529543e+06
2,Gabon,513340.0,597192.0,749078.0,983028.0,1272935.0,1711105.0,2.292573e+06
3,Burkina Faso,4783259.0,5611666.0,6932967.0,9131361.0,11882888.0,16116845.0,2.152263e+07
4,Pakistan,45954226.0,59290872.0,80624057.0,115414069.0,154369924.0,194454498.0,2.271967e+08

In [23]:
pop_array = np.array([[227948869.0, 293900563.0, 388793467.0, 516629688.0, 671212486.0, 879797419.0, 1151302081.0],
                      [4429634.0, 4606307.0, 4779535.0, 4986431.0, 5176209.0, 5363352.0, 5529543.0],
                      [513340.0, 597192.0, 749078.0, 983028.0, 1272935.0, 1711105.0, 2292573.0],
                      [4783259.0, 5611666.0, 6932967.0, 9131361.0, 11882888.0, 16116845.0, 21522626.0],
                      [45954226.0, 59290872.0, 80624057.0, 115414069.0, 154369924.0, 194454498.0, 227196741.0]])

In [24]:
df2 = pd.DataFrame(pop_array, columns=['1960', '1970', '1980', '1990', '2000', '2010', '2020'])
df2.head()

,1960,1970,1980,1990,2000,2010,2020
0,227948869.0,293900563.0,388793467.0,516629688.0,671212486.0,879797419.0,1.151302e+09
1,4429634.0,4606307.0,4779535.0,4986431.0,5176209.0,5363352.0,5.529543e+06
2,513340.0,597192.0,749078.0,983028.0,1272935.0,1711105.0,2.292573e+06
3,4783259.0,5611666.0,6932967.0,9131361.0,11882888.0,16116845.0,2.152263e+07
4,45954226.0,59290872.0,80624057.0,115414069.0,154369924.0,194454498.0,2.271967e+08

In [25]:
#Adding country to the df
country = ["Sub-Saharan Africa", "Finland", "Gabon", "Burkina Faso", "Pakistan"]
df2["Country"] = country

df2.head()

,1960,1970,1980,1990,2000,2010,2020,Country
0,227948869.0,293900563.0,388793467.0,516629688.0,671212486.0,879797419.0,1.151302e+09,Sub-Saharan Africa
1,4429634.0,4606307.0,4779535.0,4986431.0,5176209.0,5363352.0,5.529543e+06,Finland
2,513340.0,597192.0,749078.0,983028.0,1272935.0,1711105.0,2.292573e+06,Gabon
3,4783259.0,5611666.0,6932967.0,9131361.0,11882888.0,16116845.0,2.152263e+07,Burkina Faso
4,45954226.0,59290872.0,80624057.0,115414069.0,154369924.0,194454498.0,2.271967e+08,Pakistan

In [26]:
#country added to the end of df
#Moving to the first column
columns = df2.columns.to_list()
print("Before shifting: ",columns)
columns.insert(0,columns.pop())
print("After shifting :",columns)

Before shifting:  ['1960', '1970', '1980', '1990', '2000', '2010', '2020', 'Country']
After shifting : ['Country', '1960', '1970', '1980', '1990', '2000', '2010', '2020']

In [27]:
#passing this list to the df
df2 = df2[columns]
df2.head()

,Country,1960,1970,1980,1990,2000,2010,2020
0,Sub-Saharan Africa,227948869.0,293900563.0,388793467.0,516629688.0,671212486.0,879797419.0,1.151302e+09
1,Finland,4429634.0,4606307.0,4779535.0,4986431.0,5176209.0,5363352.0,5.529543e+06
2,Gabon,513340.0,597192.0,749078.0,983028.0,1272935.0,1711105.0,2.292573e+06
3,Burkina Faso,4783259.0,5611666.0,6932967.0,9131361.0,11882888.0,16116845.0,2.152263e+07
4,Pakistan,45954226.0,59290872.0,80624057.0,115414069.0,154369924.0,194454498.0,2.271967e+08

#### sampling data

In [29]:
## load data

data = pd.read_csv("world_pop.csv")

data.head()

,Country,1960,1970,1980,1990,2000,2010,2020
0,Aruba,54608.0,59106.0,62267.0,65712.0,89101.0,100341.0,106585.0
1,Africa Eastern and Southern,130692579.0,172475766.0,230967858.0,309890664.0,401600588.0,523459657.0,685112979.0
2,Afghanistan,8622466.0,10752971.0,12486631.0,10694796.0,19542982.0,28189672.0,38972230.0
3,Africa Western and Central,97256290.0,121424797.0,157825609.0,206739024.0,269611898.0,356337762.0,466189102.0
4,Angola,5357195.0,6029700.0,8330047.0,11828638.0,16394062.0,23364185.0,33428486.0

In [31]:
sample = data.sample(5,random_state= 12345)

sample.head()

,Country,1960,1970,1980,1990,2000,2010,2020
229,Chad,3028688.0,3667394.0,4408230.0,5827069.0,8259137.0,11894727.0,16644701.0
175,Nicaragua,1789684.0,2444767.0,3303309.0,4227820.0,5123222.0,5855734.0,6755895.0
199,French Polynesia,84851.0,117891.0,163591.0,211089.0,250927.0,283788.0,301920.0
220,Suriname,268396.0,379918.0,375112.0,412756.0,478998.0,546080.0,607065.0
50,Cuba,7267395.0,8869636.0,9809107.0,10626680.0,11105791.0,11290417.0,11300698.0